name: hrmax

services:
  mongo:
    image: mongo:7.0.2
    volumes:
      - mongo_data:/data/db
    networks:
      - hr-network
  api:
    build:
      context: ./hrmax-api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./hrmax-api/.env
    networks:
      - hr-network
    ports:
      - 8800:8800
    depends_on:
      - mongo

  frontend:
    build:
      context: ./hrmax-frontend
      target: production
    restart: unless-stopped
    env_file: ./hrmax-frontend/.env
    volumes:
      - ./hrmax-frontend:/app
      - /app/node_modules
    networks:
      - hr-network
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  mongo_data:
networks:
  hr-network:
    driver: bridge
